baseURL = 'https://andrezsc.com/'
title = 'Andrez Segovia'
copyright = 'Â© 2025 Andrez Segovia'

theme = 'hugo-bearcub'

defaultContentLanguage = 'en'
languageCode = 'en-us'

summaryLength = 10
disableKinds = ['rss']

enableGitInfo = true

ignoreFiles = ['content/templates', 'content/.obsidian']

[markdup]
    [markdup.highlight]
        lineNos = true
        lineNumberInTable = false
        noClasses = false

[languages]
  [languages.en]
    title = "Andrez Segovia"
    languageName = "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"


[params]
    [params.author]
        name = 'Andrez Segovia'
        email = "me@andrezsc.com"

[menus]
  [[menus.main]]
    name = 'All Categories'
    pageRef = '/categories'
    weight = 11

[taxonomies]
  category = 'categories'



